#!/usr/bin/env bash
# scripts/build-dist.sh — Phase 13: produce dist/cyferio-vpn, a single
# self-contained file that bundles every lib/*.sh module plus the
# config/template/migration assets normally read at runtime from
# CYFERIO_ROOT_DIR — so the result can be copied straight to
# /usr/local/bin/cyferio-vpn (or curl'd down) and run with no sibling
# lib/, config/, templates/, or db/ directory required, matching the
# "single script you can drop in /usr/local/bin" distribution model
# people expect from this kind of tool.
#
# GENERATED OUTPUT. Never hand-edit dist/cyferio-vpn — re-run this
# script instead; the checked-in source of truth stays the lib/*.sh
# modules and bin/cyferio-vpn's own dependency-order for-loop, which
# this script parses out of bin/cyferio-vpn directly rather than
# duplicating, so the module-load order can never drift between the
# dev entry point and the bundle.
set -Eeuo pipefail

REPO_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
OUT_DIR="${REPO_ROOT}/dist"
OUT_FILE="${OUT_DIR}/cyferio-vpn"
mkdir -p "${OUT_DIR}"

# --- 1. pull the dependency-ordered module list out of bin/cyferio-vpn ---
entry="${REPO_ROOT}/bin/cyferio-vpn"
module_line="$(grep -m1 '^for module in ' "${entry}")" || {
  echo "build-dist: could not find 'for module in ...' in ${entry}" >&2
  exit 1
}
modules_str="${module_line#for module in }"
modules_str="${modules_str%; do}"
read -r -a MODULES <<<"${modules_str}"
[[ "${#MODULES[@]}" -gt 0 ]] || { echo "build-dist: parsed an empty module list" >&2; exit 1; }

# --- 2. strip a module's shebang + its __CYFERIO_X_LOADED guard block ---
# Every lib/*.sh starts with:
#   #!/usr/bin/env bash
#   <header comment lines...>
#   if [[ -n "${__CYFERIO_X_LOADED:-}" ]]; then
#     return 0
#   fi
#   __CYFERIO_X_LOADED=1
# The guard exists to make re-sourcing the same file a no-op — meaningless
# here since each module's text appears exactly once in the bundle, and
# actively dangerous to leave in: a bare top-level `return` errors when
# the bundle is *executed* (not sourced), which is exactly how the
# installed single file runs. Strip shebang + guard, keep everything else
# byte-for-byte so shellcheck/behavior stay identical to the source module.
strip_module() {
  awk '
    NR == 1 && /^#!/ { next }
    /^if \[\[ -n "\$\{__CYFERIO_[A-Z_]+_LOADED:-\}" \]\]; then$/ { in_guard = 1; next }
    in_guard && /^  return 0$/ { next }
    in_guard && /^fi$/ { in_guard = 0; next }
    /^__CYFERIO_[A-Z_]+_LOADED=1$/ { next }
    { print }
  ' "$1"
}

# --- 3. embed a small text asset as a quoted-heredoc variable assignment ---
# Quoted delimiter ('CYFERIO_ASSET_EOF') disables all expansion inside the
# asset body regardless of its content (backticks, $-signs, etc. all pass
# through literally) — safe for arbitrary template/config/SQL text.
embed_asset() {
  local varname="$1" relpath="$2"
  printf '%s=$(cat <<'"'"'CYFERIO_ASSET_EOF'"'"'\n' "${varname}"
  cat "${REPO_ROOT}/${relpath}"
  printf '\nCYFERIO_ASSET_EOF\n)\n'
}

# --- 4. assemble ---
{
  echo '#!/usr/bin/env bash'
  echo "# cyferio-vpn — single-file build. GENERATED by scripts/build-dist.sh"
  echo "# from $(cd "${REPO_ROOT}" && git rev-parse --short HEAD 2>/dev/null || echo "unknown commit") — do not hand-edit."
  echo '#'
  echo '# This bundles lib/*.sh (dependency order taken from bin/cyferio-vpn)'
  echo '# plus config/template/migration assets that are normally read from'
  echo '# CYFERIO_ROOT_DIR at runtime. The bootstrap below runs FIRST, before'
  echo '# any module code — mirroring bin/cyferio-vpn, which resolves'
  echo '# CYFERIO_ROOT_DIR before its `source` loop, not after: several'
  echo '# modules read CYFERIO_ROOT_DIR at module-load time (e.g.'
  echo '# database.sh sets CYFERIO_MIGRATIONS_DIR from it on its very first'
  echo '# line), so the temp asset tree must already exist by the time'
  echo '# module code starts running, not merely by the time core_dispatch'
  echo '# is finally called.'
  echo
  echo 'set -Eeuo pipefail'
  echo

  echo '# ==== embedded assets (normally read from CYFERIO_ROOT_DIR) ===='
  embed_asset _CYFERIO_ASSET_CONF_EXAMPLE            config/cyferio.conf.example
  embed_asset _CYFERIO_ASSET_SERVER_CONF_TMPL         config/server.conf.tmpl
  embed_asset _CYFERIO_ASSET_CLIENT_OVPN_TMPL         templates/client.ovpn.tmpl
  embed_asset _CYFERIO_ASSET_CLIENT_CONNECT_TMPL      templates/client-connect.sh.tmpl
  embed_asset _CYFERIO_ASSET_CLIENT_DISCONNECT_TMPL   templates/client-disconnect.sh.tmpl
  embed_asset _CYFERIO_ASSET_MIGRATION_0001           db/migrations/0001_initial_schema.sql
  echo

  cat <<'BUNDLE_BOOTSTRAP'
# ==== bundle bootstrap (must run before any module code below) ====
# Resolve the real path to this file (following symlinks — e.g. installed
# as /usr/local/bin/cyferio-vpn, or a symlink into a versioned dist dir),
# same technique bin/cyferio-vpn uses for CYFERIO_SELF_PATH in the
# multi-file layout. This is the path baked into the client-connect/
# -disconnect hooks (see lib/backends/openvpn.sh's ovpn_install_hooks) —
# it must be a stable, permanent path, unlike CYFERIO_ROOT_DIR below.
_cyferio_bundle_resolve_self() {
  local src="${BASH_SOURCE[0]}"
  while [[ -L "${src}" ]]; do
    local dir
    dir="$(cd -P "$(dirname "${src}")" >/dev/null 2>&1 && pwd)"
    src="$(readlink "${src}")"
    [[ "${src}" != /* ]] && src="${dir}/${src}"
  done
  echo "${src}"
}
CYFERIO_BUNDLED=1
CYFERIO_SELF_PATH="$(_cyferio_bundle_resolve_self)"
export CYFERIO_BUNDLED CYFERIO_SELF_PATH

# CYFERIO_ROOT_DIR, by contrast, only needs to survive THIS invocation —
# every module that reads a file under it (config.example, the two
# .conf/.ovpn templates, the two hook templates, the migration .sql) does
# so once per command, not across runs. A fresh temp staging tree per
# invocation is simpler and safer than a persistent one (no stale-asset
# upgrade problem, nothing left behind if install ships a v2 template).
CYFERIO_ROOT_DIR="$(mktemp -d "${TMPDIR:-/tmp}/cyferio-vpn-assets.XXXXXX")"
export CYFERIO_ROOT_DIR
trap 'rm -rf "${CYFERIO_ROOT_DIR}"' EXIT

mkdir -p "${CYFERIO_ROOT_DIR}/config" "${CYFERIO_ROOT_DIR}/templates" "${CYFERIO_ROOT_DIR}/db/migrations"
printf '%s\n' "${_CYFERIO_ASSET_CONF_EXAMPLE}"          >"${CYFERIO_ROOT_DIR}/config/cyferio.conf.example"
printf '%s\n' "${_CYFERIO_ASSET_SERVER_CONF_TMPL}"       >"${CYFERIO_ROOT_DIR}/config/server.conf.tmpl"
printf '%s\n' "${_CYFERIO_ASSET_CLIENT_OVPN_TMPL}"       >"${CYFERIO_ROOT_DIR}/templates/client.ovpn.tmpl"
printf '%s\n' "${_CYFERIO_ASSET_CLIENT_CONNECT_TMPL}"    >"${CYFERIO_ROOT_DIR}/templates/client-connect.sh.tmpl"
printf '%s\n' "${_CYFERIO_ASSET_CLIENT_DISCONNECT_TMPL}" >"${CYFERIO_ROOT_DIR}/templates/client-disconnect.sh.tmpl"
printf '%s\n' "${_CYFERIO_ASSET_MIGRATION_0001}"         >"${CYFERIO_ROOT_DIR}/db/migrations/0001_initial_schema.sql"
BUNDLE_BOOTSTRAP
  echo

  for module in "${MODULES[@]}"; do
    src="${REPO_ROOT}/lib/${module}.sh"
    [[ -f "${src}" ]] || { echo "build-dist: missing module file ${src}" >&2; exit 1; }
    echo "# ==== module: ${module}.sh ===="
    strip_module "${src}"
    echo
  done

  echo '# ==== dispatch ===='
  echo "trap 'core_on_error \$? \$LINENO' ERR"
  echo
  echo 'core_banner'
  echo 'config_load'
  echo
  echo 'core_dispatch "$@"'
} >"${OUT_FILE}"

chmod 0755 "${OUT_FILE}"
echo "build-dist: wrote ${OUT_FILE} ($(wc -l <"${OUT_FILE}") lines)"
